services:
  # ============================
  # 1. Express API Backend
  # ============================
  backend:
    build:
      context: ./Back-End
    container_name: beautify_backend
    ports:
      - "5000:5000"
    # Because Docker ignores your .env file for security, we explicitly map the file here
    env_file:
      - ./Back-End/.env
    # Inside Docker, localhost points to the container itself, not the host machine.
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/beautify_africa
    # Tells Docker to restart the backend automatically if it ever crashes
    restart: unless-stopped

  # ============================
  # 2. React Vite Frontend
  # ============================
  frontend:
    build:
      context: ./Front-End
      # During compilation, Vite bakes the API URL in. We point it to the exposed backend.
      args:
        VITE_API_URL: http://localhost:5000
        VITE_STRIPE_PUBLISHABLE_KEY: pk_test_51RBFvFFSeF38x7miiv5gZvt0o4IiAcx8VMLJq6j4zKchX8VVwWwqgvaJtps8gZAyiWfs3pAzbNFYw8sfQ3SwaNYb009qB6Hrfq
    container_name: beautify_frontend
    # Map it to port 4173 which closely matches your Vite Preview port
    ports:
      - "4173:80"
    # Force the frontend to wait until the backend exists before booting
    depends_on:
      - backend
    restart: unless-stopped
