// utils/logger.js
const pino = require('pino');

const isTest = process.env.NODE_ENV === 'test';

const logger = pino({
  level: process.env.LOG_LEVEL || (isTest ? 'silent' : 'info'),
  timestamp: pino.stdTimeFunctions.isoTime,
  formatters: {
    level(label) {
      return { level: label };
    },
  },
  redact: {
    paths: [
      'password',
      '*.password',
      'newPassword',
      '*.newPassword',
      'oldPassword',
      '*.oldPassword',
      'pin',
      '*.pin',
      'token',
      '*.token',
      'refreshToken',
      '*.refreshToken',
      'jwt',
      '*.jwt',
      'apiKey',
      '*.apiKey',
      'clientSecret',
      '*.clientSecret',
      'secret',
      '*.secret',
      'authorization',
      'headers.authorization',
      'headers.cookie',
      'cookie',
      'headers["x-csrf-token"]',
      'headers["stripe-signature"]',
      'headers["x-paystack-signature"]',
      'creditCard',
      '*.creditCard',
      'cardNumber',
      '*.cardNumber',
      'cvv',
      '*.cvv',
      'expiry',
      '*.expiry',
      'pan',
      '*.pan',
      'securityCode',
      '*.securityCode',
      'accountNumber',
      '*.accountNumber',
      'email',
      '*.email',
      'phone',
      '*.phone',
      'phoneNumber',
      '*.phoneNumber',
      'PartyA',
      'PartyB',
      '*.PartyA',
      '*.PartyB',
      'nationalId',
      '*.nationalId',
      'taxId',
      '*.taxId',
      'ssn',
      '*.ssn',
      'address',
      '*.address',
      'shippingAddress.address',
      'shippingAddress.zip',
      'shippingAddress.phone',
      'shippingAddress.email',
    ],
    censor: '[REDACTED]',
  },
});

module.exports = logger;
